Feature/users-create
wanted-wecode-subjects/redbrick-subject pull request #39
Opened 2021-11-08 14:10 UTC by BangleCoding

## 작업 분류

- [ ] 버그 수정
- [x] 신규 기능 추가
- [ ] 리팩터링
- [ ] 테스트

## 작업 개요
- createUser 기능 추가 

## 상세 내용
- createUser 관련 기능 추가

## 집중 요망!
- 우선적으로 createUser 기능 작성한 뒤, 나머지 CRUD 기능은 로그인 기능을 구현한 뒤에 작업하기로 협의했습니다. 

resolves: #

2021-11-08 14:44 UTC, lhj0621 requested changes

2021-11-08 14:44 UTC, lhj0621 commented on src/users/users.controller.ts
> +    }
`return await this.usersService.createUser(createBody);` 으로 수정한다면 다른 소스와 통일성이 생길 거 같습니다.

2021-11-08 14:44 UTC, lhj0621 commented on src/users/users.controller.ts
> +  async createUser(@Body() createBody: CreateUserDto) {
리턴 타입 명시 부탁드립니다.

2021-11-08 14:44 UTC, lhj0621 commented
충돌도 해결 부탁드립니다.

2021-11-08 15:40 UTC, BangleCoding commented
### controller 변경 완료 
 ```ts
@Controller('users')
export class UsersController {
  constructor(private readonly usersService: UsersService) {}

  @Post()
  async createUser(@Body() createBody: CreateUserDto): Promise<User> {
    return await this.usersService.createUser(createBody);
  }
}
```
### service 변경 완료 
```ts
async createUser({
    email,
    password,
    nickname,
  }: CreateUserDto): Promise<User> {
    const existUser = this.usersRepository.findOne({ email });
    if (existUser) {
      throw new ConflictException('이미 가입된 이메일입니다.');
    }

    const user = this.usersRepository.create({ email, password, nickname });
    try {
      return await this.usersRepository.save(user);
    } catch (error) {
      throw new InternalServerErrorException(
        '회원 가입에 오류가 발생하였습니다.',
      );
    }
  }
```

### 충돌 해결 완료

=============

확인 부탁드립니다!

2021-11-09 00:57 UTC, lhj0621 approved these changes

2021-11-09 01:01 UTC, lhj0621 reviewed
혹시 커밋 하신건가요?

2021-11-09 01:31 UTC, merged